### ISSUE TITLE
Crash when opening now playing tray with certain station

### ISSUE THREAD

**Issue by codl** [segler-alex/RadioDroid#749] opened 2020-03-01 22:09 UTC
When playing station "Nova la nuit" (station uuid `7c1e82fc-11b0-11ea-a87e-52543be04c81`) if I tap the bar at the bottom of the screen with the station name, or slide it up, the app crashes.

I think this might have something to do with the station having a `data:` uri for its icon? It's also missing its icon in the stations list.

**Comment by werman** [comment] 2020-03-01 22:13
It well may be caused by icon uri. Doesn't crash on latest master. Probably was fixed by my recent fixes of icons loading.

**Closed** 2020-03-02 19:59 UTC
