### ISSUE TITLE
Support for play/pause button from headphones headset?

### ISSUE THREAD

**Issue by orschiro** [segler-alex/RadioDroid#261] opened 2017-12-17 09:55 UTC
Dear all,

I have a headphones headset that has a button to play/pause. 

Most apps support that one. 

Can RadioDroid support it as well to play/pause the playback?

Thank you!

**Comment by werman** [comment] 2017-12-17 11:34
Hello,
We support play/pause button for bluetooth headphones, it can play/pause the playback. It is supported since v0.37 which is already on Play Store and F-Droid. There is a v0.48 beta version on Play Store - you can try it too.  
Also could you provide more info about your android version and headphones model?

Related to issue #87 which was resolved by #148.

**Comment by orschiro** [comment] 2017-12-17 12:16
@werman thank you! 

- I am using version 0.48 of RadioDroid
- Android version 4.3
- Urban ears headphones (see below)

![image](https://user-images.githubusercontent.com/170947/34079354-7ad75be0-e32c-11e7-8b5f-6d42c8cd3b0f.png)

**Comment by werman** [comment] 2017-12-17 12:44
Oh, they aren't bluetooth but it shouldn't be an issue, probably... I have looked at another music app source [Jockey](https://github.com/marverenic/Jockey/blob/38aa0ca61701ae790b27153b33dad60e388ab7a5/app/src/main/java/com/marverenic/music/player/MusicPlayer.java) and it seems I didn't handle play/pause in a proper way. 

I'll try to reproduce the issue and improve the current code.

**Comment by werman** [comment] 2017-12-17 12:59
It seems indeed the inline controls do send KEYCODE_HEADSETHOOK which we don't handle (e.g it is mentioned in http://www.androidpolice.com/2016/11/08/after-years-google-to-force-android-device-oems-to-support-some-standard-headphone-inline-controls/).

**Comment by orschiro** [comment] 2017-12-17 14:07
I am afraid, I don't understand much of what you are saying but let me know whenever I can help with some testing!

**Comment by werman** [comment] 2017-12-17 14:20
I'll notify when solve the issue. And technical info here is just for anyone who wants to understand what happened and how to fix.

**Comment by orschiro** [comment] 2017-12-17 15:44
OK, thanks!

**Closed** 2018-01-13 16:51 UTC

**Comment by orschiro** [comment] 2018-01-14 09:40
@segler-alex very nice!
