### ISSUE TITLE
Playing Interrupted after Earphone Unplugged or Call Ended

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/RadioDroid#610] opened 2019-11-14 06:19 UTC
1 - The app stops playing after unplugging the earphone.
2 - After ending a call, the app reports **request for audio focus was not granted** and stops playing.
There can be options to enable or disable the cases.

**Comment by werman** [comment] 2019-11-17 15:15
1. Could be made as an option.
2. It should work, at least it worked. Someone should recheck this on emulator.

**Comment by werman** [comment] 2019-12-21 21:59
The issue is that in `onPause` we shut down player service if it's not playing anything...

**Comment by segler-alex** [comment] 2020-01-26 11:15
is this fixed?

**Comment by JensKorte** [comment] 2020-01-28 11:09
I use 0.67 from F-Droid and didn't find any fitting option, nor was the player restarted when connection. It was a headset with microphone.

**Comment by werman** [comment] 2020-01-28 11:15
> is this fixed?

"2 - After ending a call, the app reports request for audio focus was not granted and stops playing." - this is fixed.

"1 - The app stops playing after unplugging the earphone." - this work-in-progress and a part of slightly bigger changes

> I use 0.67 from F-Droid and didn't find any fitting option, nor was the player restarted when connection. It was a headset with microphone.

All mentioned changes are not released yet. And you also use old version of RadioDroid, the latest one is 0.79

**Comment by JensKorte** [comment] 2020-01-28 11:28
> All mentioned changes are not released yet. And you also use old version of RadioDroid, the latest one is 0.79

Is there a development repo for F-Droid?

**Comment by werman** [comment] 2020-01-28 11:32
> > All mentioned changes are not released yet. And you also use old version of RadioDroid, the latest one is 0.79
> 
> Is there a development repo for F-Droid?

Oh, I see there is https://f-droid.org/en/docs/Publishing_Nightly_Builds option in f-droid, no we don't use it. It would be too unstable, maybe in future when we get at least some test coverage...

**Comment by JensKorte** [comment] 2020-01-28 12:20
I thought of something like <https://f-droid.org/de/repomaker/>, <https://grobox.de/fdroid/> or <https://f-droid.org/wiki/page/Known_Repositories>

**Comment by werman** [comment] 2020-02-07 21:56
@segler-alex You can close this now.

**Comment by segler-alex** [comment] 2020-02-07 21:56
ok

**Closed by segler-alex** 2020-02-07 21:56 UTC
Labels: bug
