### ISSUE TITLE
CONFIRM BEFORE DELETE in Favorites list (starred)

### ISSUE THREAD

**Issue by kekukui** [segler-alex/RadioDroid#362] opened 2018-07-09 20:48 UTC
If you grab your device the wrong way, its too easy to accidentally delete favorite stations by sliding them off the screen.  The 'delete by sliding' feature should be replaced with some kind of delete confirm dialog.

**Comment by werman** [comment] 2018-07-09 21:11
Undo button appears after deletion for some time. Still probably it would be better to make optional confirmation dialog.

**Comment by Vrihub** [comment] 2018-10-06 16:07
BUG: The undo button only appears if you "delete by sliding", NOT if you delete by clicking on the station icon on the left: the station is instantly removed!!!

Also the undo button time is way too short, IMHO it shouldn't time out at all, to give the user a real chance of undoing.

It's still too easy to remove radios by mistake :(

**Comment by werman** [comment] 2018-10-06 20:15
Yeah, one of many small UX issues...

**Comment by Vrihub** [comment] 2019-06-08 09:22
Damn I keep deleting stations accidentally every day :)
Any chance of fixing this soon? I think this would do:

- add the undo button also when you delete by clicking on the station icon (not only when you delete by sliding)
- make the undo button timeout period infinite

**Comment by kekukui** [comment] 2019-06-13 20:21
Maybe change the delete method to one of the following:
- long press on station, with confirmation dialog
- icon for delete function in the expanding menu section (where the 5 icons appear beneath station name)

**Comment by werman** [comment] 2019-06-13 20:24
I think improving undo would do it.

**Comment by segler-alex** [comment] 2020-02-02 14:43
duplicate of #650

**Closed by segler-alex** 2020-02-02 14:43 UTC
Labels: duplicate
