### ISSUE TITLE
Could not connect to station

### ISSUE THREAD

**Issue by apuser31** [segler-alex/RadioDroid#681] opened 2020-02-05 18:53 UTC
Android Kitkat 4.4.2 phone.  Suddenly a couple days ago (early Feb) no stations would play; instead received message "Could not connect to station" at bottom.  Under Settings/Connectivity in RadioBrowser servers, option selected was "www.radio-browsers.info/webservice".  No other internet access issues with phone, including other radio and podcast apps, and I can get to that address using browser (Firefox) on that phone. 

However, a separate Android Marshmallow phone connects OK (on same Wifi network) using server "www.radio-browsers.info/webservice".  

Back on the Kitkat phone, I tried switching to "nl1.api.radio-browser.info" and "de1.api.radio-browser.info" and they both connected successfully, but switching back to default "www.radio-browsers.info/webservice" fails again with same "Could not connect to station" message.  First time encountering this issue.  Don't know what it means, and it is working again with the other servers, but I thought I should report it in case it might indicate the start of a bigger problem.  Thanks, love the app.

**Comment by twikedk** [comment] 2020-02-06 18:37
Same here, though on 4.4.4, also started around first in February and a change to one of the other servers makes it work again.

**Comment by segler-alex** [comment] 2020-02-07 21:48
i restarted the server in the morning today, there was a hickup i think, could you try again?
the next version of radiodroid (0.80) will not use the old server at all anymore and automatically fall back to other servers if the connection fails.

**Comment by twikedk** [comment] 2020-02-08 10:23
I just tested but still get same information that it can't connect. The other 3 servers are working fine so no need to dig to hard if it, as I understand, will not be using the main server from version 0.80?

**Comment by segler-alex** [comment] 2020-02-08 11:22
i just checked an older phone of mine, where i finally could reproduce this error
what version of radiodroid do you use?

yes in version 0.80, which should arrive not from now, there is an automatic fallback to other servers AND the old server is completely dropped from the list.

**Comment by segler-alex** [comment] 2020-02-08 11:25
i get the following error:

```
02-08 12:23:20.971 5042-5108/net.programmierecke.radiodroid2 D/libc-netbsd: getaddrinfo: www.radio-browser.info get result from proxy >>
02-08 12:23:20.972 5042-5108/net.programmierecke.radiodroid2 I/System.out: propertyValue:true
02-08 12:23:20.973 5042-5108/net.programmierecke.radiodroid2 I/System.out: [socket][4] connection www.radio-browser.info/37.120.178.42:443;LocalPort=47862(4000)
02-08 12:23:20.977 5042-5108/net.programmierecke.radiodroid2 I/System.out: [CDS]connect[www.radio-browser.info/37.120.178.42:443] tm:4
02-08 12:23:21.014 5042-5108/net.programmierecke.radiodroid2 I/System.out: [socket][/192.168.0.217:47862] connected
02-08 12:23:21.015 5042-5108/net.programmierecke.radiodroid2 I/System.out: [CDS]rx timeout:3000
02-08 12:23:21.047 5042-5108/net.programmierecke.radiodroid2 E/NativeCrypto: Unknown error during handshake
02-08 12:23:21.048 5042-5108/net.programmierecke.radiodroid2 I/System.out: [CDS]close[47862]
02-08 12:23:21.049 5042-5108/net.programmierecke.radiodroid2 I/System.out: close [socket][/0.0.0.0:47862]
02-08 12:23:21.049 5042-5108/net.programmierecke.radiodroid2 I/System.out: close [socket][/0.0.0.0:47862]
02-08 12:23:21.050 5042-5108/net.programmierecke.radiodroid2 I/System.out: [socket][5] connection www.radio-browser.info/37.120.178.42:443;LocalPort=39957(4000)
02-08 12:23:21.051 5042-5108/net.programmierecke.radiodroid2 I/System.out: [CDS]connect[www.radio-browser.info/37.120.178.42:443] tm:4
02-08 12:23:21.090 5042-5108/net.programmierecke.radiodroid2 I/System.out: [socket][/192.168.0.217:39957] connected
02-08 12:23:21.090 5042-5108/net.programmierecke.radiodroid2 I/System.out: [CDS]rx timeout:3000
02-08 12:23:21.121 5042-5108/net.programmierecke.radiodroid2 E/NativeCrypto: Unknown error during handshake
02-08 12:23:21.121 5042-5108/net.programmierecke.radiodroid2 I/System.out: [CDS]close[39957]
02-08 12:23:21.122 5042-5108/net.programmierecke.radiodroid2 I/System.out: close [socket][/0.0.0.0:39957]
02-08 12:23:21.123 5042-5108/net.programmierecke.radiodroid2 E/UTIL: downloadFeed() javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5de4f918: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x59b38890:0x00000000)
```

**Comment by segler-alex** [comment] 2020-02-08 11:25
i use letsencrypt for ssl on the server, maybe there was some change which is not supported by older ssl libraries on the phones ?

**Comment by segler-alex** [comment] 2020-02-08 11:26
this error is NOT intended!
but i still would encourage people to update the radiodroid version to the most current one

**Comment by segler-alex** [comment] 2020-02-08 11:28
we are all doing this in our freetime, so we always only look at the latest version for bugs.

**Comment by segler-alex** [comment] 2020-02-08 11:39
please also add your android version

**Comment by twikedk** [comment] 2020-02-08 11:41
RadioDroid 0.79 from F-Droid
Android 4.4.4

The app is still awesome :-) so no need to worry and after I found that I just needed to switch server I was up and running again. Looking forward to the release of 0.80.

**Comment by segler-alex** [comment] 2020-02-08 11:44
thanks, there is definitely something that must have changed on the main server. still searching what it is...

**Comment by segler-alex** [comment] 2020-02-08 12:49
now i know, certbot made an upgrade and changed apache server options.
https://github.com/certbot/certbot/commit/b1a8e7175b1d7ee9d7bd16d5ba9b3ddd055c80db#diff-e03411e91567c5a5818441a09d444ed2

after i reverted it, it worked on my old phone again.
please test.

**Comment by twikedk** [comment] 2020-02-08 12:55
Yes, now it works here again :-)

**Comment by segler-alex** [comment] 2020-02-08 15:17
[RadioDroid-play-debug-DEV-0.79-8eee7f3.zip](https://github.com/segler-alex/RadioDroid/files/4174498/RadioDroid-play-debug-DEV-0.79-8eee7f3.zip)
could you try this out on your device?
i reverted the server change. so the default version breaks again, i want to find a solution for older phones

**Comment by twikedk** [comment] 2020-02-08 20:12
Yes I will but not until Sunday if that is OK :-)

**Comment by twikedk** [comment] 2020-02-08 20:26
OK I have just tested but I'm not able to do anything because it wants me to have Google Play updated and on that tablet this is not gonna happen :-) as it is meant only for F-Droid. So if I need to test, it will have to be a version meant for F-droid, sorry

**Comment by apuser31** [comment] 2020-02-08 21:36
I tried RadioDroid-play-debug-DEV-0.79-8eee7f3.zip on my Android 4.4.2 phone but nothing would connect, got "Could not connect to station" on each station.

**Comment by apuser31** [comment] 2020-02-08 21:49
There was something similar with the AntennaPod app recently (issue 3735); it was fixed using something called Google Trust Provider -- I don't understand the specifics but it fixed SSL handshake errors on older devices.  Detail at https://github.com/AntennaPod/AntennaPod/commit/2d93af6707d55834b5d1412952b8acd8d08b03a4 in case it helps ...?

**Comment by segler-alex** [comment] 2020-02-09 00:03
thank you for the hint, but as i understand it, you can only do that if your mobile actually has google things installed. if you choose to go without google (as for example some of the people of f-droid) you can't use google helpers.

i tried it on my old phone, and now i got it to work with your tipp. but still i have to search how to emulate google behaviour without using google ...

**Comment by segler-alex** [comment] 2020-02-09 00:51
i implemented your solution, it will be in the next release. but still i have to find something for fdroid

**Comment by segler-alex** [comment] 2020-02-09 02:40
i did all that i could do for f-droid, there will still be some devices that are not supported.
play store should be covered.

**Closed by segler-alex** 2020-02-09 02:40 UTC
Labels: bug

**Comment by apuser31** [comment] 2020-02-09 02:41
OK thanks and sorry for not knowing more about it -- AntennaPod is also available on F-Droid so i didn't realize they had different code, i  just assumed they were the same.  As I said, no clue here.  Anyway didn't mean to confuse things, the issues seemed kinda similar

**Comment by segler-alex** [comment] 2020-02-09 02:54
i looked it up, they have the same problem with the F-Droid version

you can read at the bottom of this issue
https://github.com/AntennaPod/AntennaPod/issues/2814

**Comment by segler-alex** [comment] 2020-02-09 02:55
some people report it as fixed and some people still have the problem

**Comment by segler-alex** [comment] 2020-02-09 03:02
does antennapod work for you in the f-droid version on the same phone as you tried radiodroid with?

**Comment by apuser31** [comment] 2020-02-09 03:10
i think i have the google play antennapod version since i was participating in beta testing but i could try the f-droid version tomorrow if it would help

**Comment by apuser31** [comment] 2020-02-10 18:34
You are correct -- I uninstalled AntennaPod and installed the apk from F-Droid -- and all the SSL handshake failures came back.  (I will go back to the Google Play version since as you said they must have different functionality.)  Thanks for looking into this.
